### ISSUE TITLE
[Bug]: DependencyDepth drastically increases the build time of builds (as in an hour vs a minute)

### ISSUE THREAD

**Issue by lexi-the-cute** [danielschemmel/build-info#19]
This is the build with (https://github.com/lexi-the-cute/catgirl-engine/actions/runs/8025125275/job/21925082182):

```rust
let mut depth: DependencyDepth = DependencyDepth::Depth(8);
```

This is the build with no DependencyDepth: https://github.com/lexi-the-cute/catgirl-engine/actions/runs/8025100333/job/21925009610

I've attached the build timings for no dependency depth below:
[No DependencyDepth](https://github.com/danielschemmel/build-info/files/14390211/CatgirlEngine-Linux-x86_64-GNU-Zip-No-DependencyDepth.zip)

The one with the dependency depth is still building and will likely continue to be building for another 45 minutes (after I clock into work)

**Comment by lexi-the-cute** [comment]
This one is dependency depth 8:

[CatgirlEngine-Linux-x86_64-GNU-Zip-DependencyDepth-8.zip](https://github.com/danielschemmel/build-info/files/14390452/CatgirlEngine-Linux-x86_64-GNU-Zip-DependencyDepth-8.zip)

I guess since I fixed caching, it halved the build time

**Comment by danielschemmel** [comment]
While it makes sense that the build time increases somewhat, I would expect increases on the order of fractions of seconds on the initial build (iterative builds can have a larger impact, as build-info requires rerunning the build-script on various changes, so that it can update its information).

**Comment by danielschemmel** [comment]
I can reproduce this issue locally, and will look into it further

**Comment by danielschemmel** [comment]
Alright, it seems like the generated function is large enough (~36k lines in this case) that rustc basically flatlines for a while, when it tries to optimize the big initializer. (This might also contribute to #16, altough rust-analyzer should still not overflow the stack.) I did not expect to run into this issue so soon.

The simple solution would be to just add a serialized blob and deserialize this using functions that are much smaller (i.e., make serde a runtime dependency or handroll some specific code). The more complex solution would be to optimize this function in such a way that rustc does not cough up blood, when looking at it.

**Comment by danielschemmel** [comment]
Validated: just using serde/bincode gets rid of the optimization problem

**Comment by danielschemmel** [comment]
7df0c9a contains a first variant of this mechanism.
